/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.City;
import model.Community;
import model.House;
import model.MainSystem;
import model.Patient;
import model.Person;
import model.PersonDirectory;

/**
 *
 * @author meghanshubhatt
 */
public class ViewUpdatePerson extends javax.swing.JPanel {

    /**
     * Creates new form ViewUpdatePerson
     */
    private JPanel userProcessContainer;
    private PersonDirectory personDirectory;
    private Person person;
    public int selectedRowIndex;
    private City city;
    private MainSystem system; 
    public ViewUpdatePerson(JPanel upc, PersonDirectory pd, int selecteRowIndex,City cty, MainSystem sys) {
        initComponents();
        userProcessContainer = upc;
        personDirectory = pd;
         selectedRowIndex = selecteRowIndex;
         city = cty;
         system = sys;
         getSelectedRowValues();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtFname = new javax.swing.JTextField();
        txtPhonenumber = new javax.swing.JTextField();
        txtAge = new javax.swing.JTextField();
        txtLname = new javax.swing.JTextField();
        Save = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtHouseName = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtHouseAddress = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtHouseNumber = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtCityName = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtCommunityName = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        genderCombo = new javax.swing.JComboBox<>();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("Last Name: ");

        jLabel2.setText("Phone Number: ");

        jLabel3.setText("First Name: ");

        jLabel4.setText("Gender:");

        jLabel5.setText("Age: ");

        txtPhonenumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPhonenumberActionPerformed(evt);
            }
        });

        Save.setText("Update !");
        Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveActionPerformed(evt);
            }
        });

        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jLabel7.setText("House Name: ");

        jLabel8.setText("House Number: ");

        jLabel9.setText("House Address: ");

        jLabel10.setText("City Name ");

        jLabel11.setText("Community Name");

        jLabel12.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel12.setText("                                                         Update Person Details !");

        genderCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", "Other" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(btnBack)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Save)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtLname, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtFname, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(genderCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtPhonenumber, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(196, 196, 196)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10))
                                .addGap(28, 28, 28)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtHouseNumber, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCityName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtHouseName)
                                    .addComponent(txtHouseAddress)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(18, 18, 18)
                                .addComponent(txtCommunityName, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(0, 135, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 611, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(287, 287, 287))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBack)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtFname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(txtCityName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtLname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(txtCommunityName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtHouseName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtHouseNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(genderCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtHouseAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txtPhonenumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(72, 72, 72)
                .addComponent(Save)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1039, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 433, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtPhonenumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPhonenumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPhonenumberActionPerformed

    private void SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveActionPerformed
        // TODO add your handling code here:
        Person person = (Person) personDirectory.getPersonList().get(selectedRowIndex);
        
//              if (txtCity.getText().trim().isEmpty()){
//            JOptionPane.showMessageDialog(this, "City is Empty!");
//            txtCity.grabFocus();
//            return;
//        }
//        else
//        {ls.get(selecteRowIndex).setisCity(txtCity.getText());}
        
        // FIRST NAME
           if (txtFname.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(this, "First Name is Empty!");
            txtFname.grabFocus();
            return;
            }
        else
           {
              person.setfName(txtFname.getText());
                       };
                       
                               // LAST NAME
         if (txtLname.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(this, "Last Name is Empty!");
            txtLname.grabFocus();
            return;
            }
        else
           {
              person.setlName(txtLname.getText());
                       };
        
        // AGE
                try{
            int age = Integer.parseInt(txtAge.getText());

            if (age < 0)
            {
                JOptionPane.showMessageDialog(this, "Input Valid Age !");
                txtAge.grabFocus();
                return;

            }

            person.setAge(Integer.parseInt(txtAge.getText()));
        }
        catch(NumberFormatException e)
        {JOptionPane.showMessageDialog(this, "Input Valid Age !");
            txtAge.grabFocus();
            return;
        }
        
        
       
        person.setGender(genderCombo.getSelectedItem().toString());
        
        // PHONE NUMBER
        
                
                try{
            long phoneNumber = Long.parseLong(txtPhonenumber.getText());

            if (String.valueOf(phoneNumber).length() != 10)
            {
                JOptionPane.showMessageDialog(this, "Input Valid Telephone Number !");
                txtPhonenumber.grabFocus();
                return;

            }
            
            person.setPhoneNumber(Long.parseLong(txtPhonenumber.getText()));
        }
        catch(NumberFormatException e)
        {JOptionPane.showMessageDialog(this, "Input Valid Telephone Number !");
            txtPhonenumber.grabFocus();
            return;
        }
        
                /// CITY
                
         if (txtCityName.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(this, "City is Empty!");
            txtCityName.grabFocus();
            return;
        }
        else
        { city = system.addCity(txtCityName.getText());}
        
         // COMMUNITY - HOME
         
        boolean flag = true; 
         
         try {
         
         int housenumber = Integer.parseInt(txtHouseNumber.getText());    
         
         if (txtCommunityName.getText().trim().isEmpty() || txtHouseName.getText().trim().isEmpty() || txtHouseAddress.getText().trim().isEmpty()
                 || txtHouseAddress.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(this, "Input Data is Empty!");
            flag=false;
            return;
        }
             System.out.println("ui.AddPersonPanel.SaveActionPerformed()");
         if (flag==true){
         Community community  = city.AddCommunity(txtCommunityName.getText());
        
        community.setCity(city.getCityName());
             

        House house = community.makeHouse();
        
        house.setHouseName(txtHouseName.getText());
        house.setHouseNumber(Integer.parseInt(txtHouseNumber.getText()));
        house.setHouseAddress(txtHouseAddress.getText());
   
        house.setCommunity(community);
        person.setHouse(house);
        //personDirectory.addNewPerson(person);
        personDirectory.saveFile();
        
        
           JOptionPane.showMessageDialog(null, "Person added successfully!!", "Info", JOptionPane.INFORMATION_MESSAGE);
         }
         
         }
         catch(NumberFormatException e) {
         JOptionPane.showMessageDialog(this, "Input Valid Home Number !");
          
            return;}
        

    }//GEN-LAST:event_SaveActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed

        backAction();
    }//GEN-LAST:event_btnBackActionPerformed
    private void backAction(){
        userProcessContainer.remove(this);
        Component [] componentArray = userProcessContainer.getComponents();
        Component c = componentArray[componentArray.length-1];
        ViewPersonPanel mp = (ViewPersonPanel) c;
        mp.refreshTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Save;
    private javax.swing.JButton btnBack;
    private javax.swing.JComboBox<String> genderCombo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtCityName;
    private javax.swing.JTextField txtCommunityName;
    private javax.swing.JTextField txtFname;
    private javax.swing.JTextField txtHouseAddress;
    private javax.swing.JTextField txtHouseName;
    private javax.swing.JTextField txtHouseNumber;
    private javax.swing.JTextField txtLname;
    private javax.swing.JTextField txtPhonenumber;
    // End of variables declaration//GEN-END:variables

    private void getSelectedRowValues() {
        Person s = new Person();
        s = personDirectory.getPersonList().get(selectedRowIndex);
        txtFname.setText(s.getfName());
        txtLname.setText(s.getlName());
        txtAge.setText(String.valueOf(s.getAge()));
        genderCombo.setSelectedItem(s.getGender());
        txtPhonenumber.setText(String.valueOf(s.getPhoneNumber()));
        txtCityName.setText(String.valueOf(s.getHouse().getCommunity().getCity()));
        txtCommunityName.setText(s.getHouse().getCommunity().getCommunityName());
        txtHouseName.setText(s.getHouse().getHouseName());
        txtHouseNumber.setText(String.valueOf(s.getHouse().getHouseNumber()));
        txtHouseAddress.setText(s.getHouse().getHouseAddress());
    }
}
